name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # matches GitHub runner logs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: |
          flake8 . --max-line-length=120

      - name: Train to generate artifacts
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          test -f data/census.csv || (echo "data/census.csv not found"; exit 1)
          python train_model.py

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q
