name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Show Python & pip
        run: |
          python -V
          pip -V

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: |
          flake8 . --max-line-length=120

      - name: Ensure dataset
        run: |
          mkdir -p data
          if [ ! -f data/census.csv ]; then
            curl -L -o data/census.csv https://raw.githubusercontent.com/udacity/nd0821-c3-starter-code/master/starter/data/census.csv
          fi

      - name: Train to generate artifacts
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python train_model.py

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q
