name: Python CI
on:
  push:
    branches: [ main, p2-dev-clean ]
  pull_request:
    branches: [ main, p2-dev-clean ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Train model artifacts
        run: |
          python train_model.py --data-path data/census.csv --target salary
      - name: Lint
        run: flake8 .
      - name: Test
        run: pytest -q
